apiVersion: v1
kind: Service
metadata:
  name: gandalf-colombo-demo-service
spec:
  type: NodePort
  selector:
    app: gandalf-colombo-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080